### ISSUE TITLE
csadfsadf

### ISSUE THREAD

**Issue by mehemtizer** [MicrosoftDocs/architecture-center.tr-tr#2]
[Geri bildiriminizi buraya girin]

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: a0024106-00f7-34d8-57cb-30029ec5f891
* Version Independent ID: 3dd1fa60-26f7-16e7-4524-1b68c7f9d26f
* Content: [Kurumsal Bulutu benimseme: Azure nasıl çalışır?](https://docs.microsoft.com/tr-tr/azure/architecture/cloud-adoption/getting-started/what-is-azure)
* Content Source: [docs/cloud-adoption/getting-started/what-is-azure.md](https://github.com/mspnp/architecture-center/blob/live-sxs/docs/cloud-adoption/getting-started/what-is-azure.md)
* Service: **architecture-center**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Empty
